services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  frontend_test:
    image: node:20-bullseye
    working_dir: /app
    volumes:
      - ./frontend:/app:ro
      - /app/node_modules
    command: sh -c "npm ci && npm test"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
